Repository Pixailz/ft_transcendence, pull requests merged in 2023-09, with the labels that each got.

#117 A2F Front
  .gitignore
  src/angularjs/package-lock.json
  src/angularjs/package.json
  src/angularjs/src/app/app.module.ts
  src/angularjs/src/app/components/avatar/avatar.component.ts
  src/angularjs/src/app/components/errordialog/errordialog.component.html
  src/angularjs/src/app/components/errordialog/errordialog.component.scss
  src/angularjs/src/app/components/errordialog/errordialog.component.spec.ts
  src/angularjs/src/app/components/errordialog/errordialog.component.ts
  src/angularjs/src/app/components/twofaform/twofaform.component.html
  src/angularjs/src/app/components/twofaform/twofaform.component.scss
  src/angularjs/src/app/components/twofaform/twofaform.component.ts
  src/angularjs/src/app/environments/environment.common.ts
  src/angularjs/src/app/layout/authenticated-layout.component.html
  src/angularjs/src/app/layout/authenticated-layout.component.ts
  src/angularjs/src/app/pages/login/login.component.ts
  src/angularjs/src/app/pages/profile/profile.component.html
  src/angularjs/src/app/pages/profile/profile.component.scss
  src/angularjs/src/app/pages/user-profile/user-profile.component.html
  src/angularjs/src/app/pages/user-profile/user-profile.component.scss
  src/angularjs/src/app/pages/user-profile/user-profile.component.ts
  src/angularjs/src/app/services/global-error-handler.service.ts
  src/angularjs/src/app/services/user.service.ts
  src/angularjs/src/styles.scss
  src/nestjs/src/adapter/errorlog.controller.ts
  src/nestjs/src/app.module.ts
  src/nestjs/src/main.ts
  src/nestjs/src/modules/database/user/entity.ts
  src/nestjs/src/modules/twofa/twofa.controller.ts
  src/nestjs/src/modules/twofa/twofa.service.ts
Labels: 🔜 FRONT

#125 create friendRequest with http_request
  src/angularjs/src/app/app.module.ts
  src/angularjs/src/app/components/errordialog/errordialog.component.html
  src/angularjs/src/app/components/errordialog/errordialog.component.scss
  src/angularjs/src/app/components/errordialog/errordialog.component.spec.ts
  src/angularjs/src/app/components/errordialog/errordialog.component.ts
  src/angularjs/src/app/components/flat-button/flat-button.component.ts
  src/angularjs/src/app/components/flat-list/flat-list.component.html
  src/angularjs/src/app/components/flat-list/flat-list.component.scss
  src/angularjs/src/app/components/flat-list/flat-list.component.spec.ts
  src/angularjs/src/app/components/flat-list/flat-list.component.ts
  src/angularjs/src/app/components/header/header.component.html
  src/angularjs/src/app/components/header/header.component.scss
  src/angularjs/src/app/components/header/header.component.ts
  src/angularjs/src/app/components/notification/notification.component.html
  src/angularjs/src/app/components/notification/notification.component.scss
  src/angularjs/src/app/components/notification/notification.component.spec.ts
  src/angularjs/src/app/components/notification/notification.component.ts
  src/angularjs/src/app/interfaces/chat.interface.ts
  src/angularjs/src/app/layout/authenticated-layout.component.html
  src/angularjs/src/app/pages/profile/profile.component.html
  src/angularjs/src/app/pages/profile/profile.component.scss
  src/angularjs/src/app/pages/profile/profile.component.ts
  src/angularjs/src/app/services/back.service.ts
  src/angularjs/src/app/services/friend-request.service.ts
  src/angularjs/src/app/services/global-error-handler.service.ts
  src/angularjs/src/app/services/user.service.ts
  src/angularjs/src/app/services/ws.gateway.ts
  src/nestjs/src/adapter/errorlog.controller.ts
  src/nestjs/src/adapter/user/controller.ts
  src/nestjs/src/modules/database/friend/controller.ts
  src/nestjs/src/modules/database/friend/service.ts
  src/nestjs/src/modules/database/friendRequest/controller.ts
  src/nestjs/src/modules/database/friendRequest/service.ts
  src/nestjs/src/websocket/chat/chat.service.ts
  src/nestjs/src/websocket/friendRequest/friendRequest.service.ts
  src/nestjs/src/websocket/ws.gateway.ts
  src/nestjs/src/websocket/ws.module.ts
Labels: 📚 SUBJECT, 🔙 BACK, 🔜 FRONT

#136 fix merge
  src/nestjs/src/modules/database/friendRequest/service.ts
Labels: 🐛 BUG

#149 Create Private channel
  src/angularjs/src/app/pages/chat-channel/chat-channel.component.html
  src/angularjs/src/app/pages/chat-channel/chat-channel.component.ts
  src/angularjs/src/app/services/websocket/gateway.ts
  src/nestjs/src/adapter/chatRoom/service.ts
  src/nestjs/src/websocket/chat/chat-channel.service.ts
  src/nestjs/src/websocket/ws.gateway.ts
Labels: 🚑️ CRITICAL, 📚 SUBJECT, 🔄 FRONT/BACK

#150 143 implement mute / ban / block
  docker-compose-dev.yaml
  src/angularjs/src/app/environments/environment.common.ts
  src/angularjs/src/app/environments/environment.dev.ts
  src/angularjs/src/app/interfaces/chat-channel.interface.ts
  src/angularjs/src/app/interfaces/user-chat-room.interface.ts
  src/angularjs/src/app/pages/chat-channel/chat-channel.component.html
  src/angularjs/src/app/pages/chat-channel/chat-channel.component.scss
  src/angularjs/src/app/pages/chat-channel/chat-channel.component.ts
  src/angularjs/src/app/pages/chat-dm/chat-dm.component.html
  src/angularjs/src/app/pages/profile/profile.component.html
  src/angularjs/src/app/pages/profile/profile.component.ts
  src/angularjs/src/app/services/websocket/chat/channel/service.ts
  src/angularjs/src/app/services/websocket/chat/chatroom.service.ts
  src/angularjs/src/app/services/websocket/friend/service.ts
  src/angularjs/src/app/services/websocket/gateway.ts
  src/nestjs/src/adapter/chatRoom/service.ts
  src/nestjs/src/adapter/user/service.ts
  src/nestjs/src/app.module.ts
  src/nestjs/src/modules/database/blocked/controller.ts
  src/nestjs/src/modules/database/blocked/dto.ts
  src/nestjs/src/modules/database/blocked/entity.ts
  src/nestjs/src/modules/database/blocked/service.ts
  src/nestjs/src/modules/database/chatRoom/service.ts
  src/nestjs/src/modules/database/database.module.ts
  src/nestjs/src/modules/database/friend/service.ts
  src/nestjs/src/modules/database/friendRequest/service.ts
  src/nestjs/src/modules/database/gameInfo/service.ts
  src/nestjs/src/modules/database/muted/controller.ts
  src/nestjs/src/modules/database/muted/dto.ts
  src/nestjs/src/modules/database/muted/entity.ts
  src/nestjs/src/modules/database/muted/service.ts
  src/nestjs/src/modules/database/notification/controller.ts
  src/nestjs/src/modules/database/notification/entity.ts
  src/nestjs/src/modules/database/notification/service.ts
  src/nestjs/src/modules/database/user/controller.ts
  src/nestjs/src/modules/database/user/entity.ts
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/modules/database/userChatRoom/dto.ts
  src/nestjs/src/modules/database/userChatRoom/entity.ts
  src/nestjs/src/modules/database/userChatRoom/service.ts
  src/nestjs/src/sanitize-object.ts
  src/nestjs/src/websocket/chat/chat-channel.service.ts
  src/nestjs/src/websocket/chat/chat-dm.service.ts
  src/nestjs/src/websocket/friend/friend.service.ts
  src/nestjs/src/websocket/gateway.ts
  src/nestjs/src/websocket/module.ts
  src/nestjs/src/websocket/notifications/notifications.service.ts
  src/nestjs/src/websocket/service.ts
  src/nestjs/src/websocket/socket.service.ts
Labels: 📚 SUBJECT, 🔄 FRONT/BACK

#160 159 refactor profile front
  src/angularjs/src/app/animations.ts
  src/angularjs/src/app/app.module.ts
  src/angularjs/src/app/components/avatar/avatar.component.html
  src/angularjs/src/app/components/avatar/avatar.component.scss
  src/angularjs/src/app/components/flat-list/flat-list.component.scss
  src/angularjs/src/app/components/header/header.component.html
  src/angularjs/src/app/components/header/header.component.ts
  src/angularjs/src/app/components/notification/friend-req-received/friend-req-received.component.ts
  src/angularjs/src/app/components/notification/notification.component.ts
  src/angularjs/src/app/components/twofaform/twofaform.component.scss
  src/angularjs/src/app/directives/click-out.directive.spec.ts
  src/angularjs/src/app/directives/click-out.directive.ts
  src/angularjs/src/app/pages/register/register.component.html
  src/angularjs/src/app/pages/register/register.component.scss
  src/angularjs/src/app/pages/register/register.component.ts
  src/angularjs/src/app/pages/user-profile/user-profile.component.html
  src/angularjs/src/app/pages/user-profile/user-profile.component.scss
  src/angularjs/src/app/pages/user-profile/user-profile.component.ts
  src/angularjs/src/app/services/back.service.ts
  src/angularjs/src/app/services/websocket/notification/service.ts
  src/angularjs/src/styles.scss
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/modules/twofa/twofa.service.ts
Labels: 🔄 FRONT/BACK
