Repository Pixailz/ft_transcendence, pull requests merged in 2023-10, with the labels that each got.

#167 CD: more modulable setup
  .github/workflows/CD.yaml
Labels: 🤖 ACTIONS

#165 Fix matchmaking + reconnect
  src/angularjs/package-lock.json
  src/angularjs/package.json
  src/angularjs/src/app/components/game/started/started.component.ts
  src/angularjs/src/app/environments/environment.common.ts
  src/angularjs/src/app/pages/game/game.component.html
  src/angularjs/src/app/services/websocket/game/service.ts
  src/angularjs/src/app/services/websocket/gateway.ts
  src/nestjs/src/websocket/game/game.interface.ts
  src/nestjs/src/websocket/game/game.service.ts
  src/nestjs/yarn.lock
Labels: 🚑️ CRITICAL, 🔄 FRONT/BACK

#175 link games info and scores to db
  src/angularjs/src/app/components/game/started/started.component.ts
  src/nestjs/src/adapter/leaderboard.controller.ts
  src/nestjs/src/modules/database/database.module.ts
  src/nestjs/src/modules/database/friendRequest/service.ts
  src/nestjs/src/modules/database/game/gameInfo/controller.ts
  src/nestjs/src/modules/database/game/gameInfo/dto.ts
  src/nestjs/src/modules/database/game/gameInfo/entity.ts
  src/nestjs/src/modules/database/game/gameInfo/service.ts
  src/nestjs/src/modules/database/game/player-score/dto.ts
  src/nestjs/src/modules/database/game/player-score/entity.ts
  src/nestjs/src/modules/database/game/player-score/service.ts
  src/nestjs/src/modules/database/gameInfo/dto.ts
  src/nestjs/src/modules/database/gameInfo/entity.ts
  src/nestjs/src/modules/database/sanitize-object.ts
  src/nestjs/src/modules/database/user/entity.ts
  src/nestjs/src/websocket/game/game.interface.ts
  src/nestjs/src/websocket/game/game.service.ts
Labels: 🚑️ CRITICAL, 📚 SUBJECT, 🔄 FRONT/BACK

#180 179 user profile stats
  src/angularjs/src/app/app.module.ts
  src/angularjs/src/app/components/user-stats/user-stats.component.css
  src/angularjs/src/app/components/user-stats/user-stats.component.html
  src/angularjs/src/app/components/user-stats/user-stats.component.spec.ts
  src/angularjs/src/app/components/user-stats/user-stats.component.ts
  src/angularjs/src/app/pages/profile/profile.component.html
  src/angularjs/src/app/pages/profile/profile.component.ts
  src/nestjs/src/adapter/game/controller.ts
  src/nestjs/src/adapter/game/module.ts
  src/nestjs/src/app.module.ts
  src/nestjs/src/modules/database/game/gameInfo/entity.ts
  src/nestjs/src/modules/database/game/gameInfo/service.ts
  src/nestjs/src/modules/database/game/player-score/service.ts
  src/nestjs/src/modules/database/user/entity.ts
Labels: 📚 SUBJECT, 🔄 FRONT/BACK

#186 update package + fix alerts
  src/angularjs/package-lock.json
  src/nestjs/package-lock.json
  src/nestjs/package.json
  src/nestjs/yarn.lock
Labels: dependencies

#168 (#127) add external player
  src/angularjs/src/app/components/twofaform/twofaform.component.ts
  src/angularjs/src/app/pages/chat-channel/chat-channel.component.html
  src/angularjs/src/app/pages/chat-channel/chat-channel.component.ts
  src/angularjs/src/app/pages/login/login.component.html
  src/angularjs/src/app/pages/login/login.component.scss
  src/angularjs/src/app/pages/login/login.component.ts
  src/angularjs/src/app/pages/register/register.component.ts
  src/angularjs/src/app/pages/user-profile/user-profile.component.html
  src/angularjs/src/app/pages/user-profile/user-profile.component.scss
  src/angularjs/src/app/services/back.service.ts
  src/angularjs/src/styles.scss
  src/nestjs/src/adapter/chatRoom/service.ts
  src/nestjs/src/addons/bcrypt.wrapper.ts
  src/nestjs/src/modules/auth/controller.ts
  src/nestjs/src/modules/auth/module.ts
  src/nestjs/src/modules/auth/service.ts
  src/nestjs/src/modules/database/sanitize-object.ts
  src/nestjs/src/modules/database/user/dto.ts
  src/nestjs/src/modules/database/user/entity.ts
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/websocket/chat/chat-channel.service.ts
  src/nestjs/src/websocket/module.ts
  test.md
Labels: 🔄 FRONT/BACK

#183 (#182) Finish Game
  src/angularjs/src/app/app-routing.module.ts
  src/angularjs/src/app/app.module.ts
  src/angularjs/src/app/components/flat-list/flat-list.component.html
  src/angularjs/src/app/components/game/invite-dialog/game-invite-dialog.component.html
  src/angularjs/src/app/components/game/invite-dialog/game-invite-dialog.component.scss
  src/angularjs/src/app/components/game/invite-dialog/game-invite-dialog.component.ts
  src/angularjs/src/app/components/game/lobby/lobby.component.html
  src/angularjs/src/app/components/game/lobby/lobby.component.ts
  src/angularjs/src/app/components/game/options-dialog/options-dialog.component.html
  src/angularjs/src/app/components/game/options-dialog/options-dialog.component.scss
  src/angularjs/src/app/components/game/options-dialog/options-dialog.component.spec.ts
  src/angularjs/src/app/components/game/options-dialog/options-dialog.component.ts
  src/angularjs/src/app/components/game/started/started.component.html
  src/angularjs/src/app/components/game/started/started.component.scss
  src/angularjs/src/app/components/game/started/started.component.ts
  src/angularjs/src/app/components/game/waiting/waiting.component.html
  src/angularjs/src/app/components/game/waiting/waiting.component.ts
  src/angularjs/src/app/components/notification/game-invite/game-invite.component.html
  src/angularjs/src/app/components/notification/game-invite/game-invite.component.scss
  src/angularjs/src/app/components/notification/game-invite/game-invite.component.ts
  src/angularjs/src/app/components/notification/notification.component.ts
  src/angularjs/src/app/interfaces/game/actors/powerup.ts
  src/angularjs/src/app/interfaces/game/game-room.interface.ts
  src/angularjs/src/app/pages/game/game.component.ts
  src/angularjs/src/app/services/websocket/game/service.ts
  src/angularjs/src/app/services/websocket/gateway.ts
  src/angularjs/src/app/services/websocket/notification/service.ts
  src/angularjs/src/assets/powerups/death.png
  src/angularjs/src/assets/powerups/size.png
  src/angularjs/src/assets/powerups/speed.png
  src/angularjs/src/assets/powerups/sticky.png
  src/angularjs/src/styles.scss
  src/nestjs/src/modules/database/notification/entity.ts
  src/nestjs/src/websocket/game/game.interface.ts
  src/nestjs/src/websocket/game/game.service.ts
  src/nestjs/src/websocket/gateway.ts
  src/nestjs/src/websocket/notifications/notifications.service.ts
Labels: 📚 SUBJECT, 🔄 FRONT/BACK

#209 lilfix (#197,#198, #199, #207, snyk)
  .github/workflows/CI-docker.yaml
  LICENSE
  README.md
  build/postgresql/Dockerfile
  src/angularjs/package-lock.json
  src/angularjs/package.json
  src/angularjs/src/app/components/notification/friend-req-received/friend-req-received.component.html
  src/angularjs/src/app/components/notification/friend-req-received/friend-req-received.component.scss
  src/angularjs/src/app/components/notification/notification.component.ts
  src/angularjs/src/app/environments/environment.dev.ts
  src/angularjs/src/app/services/websocket/notification/service.ts
  src/nestjs/package-lock.json
  src/nestjs/src/websocket/notifications/notifications.service.ts
  src/nestjs/yarn.lock
  test.md
Labels: 📝 DOCUMENTATION, dependencies, 🔙 BACK, 🤖 ACTIONS

#223 new ingame status
  src/angularjs/src/app/components/user-tooltip/user-tooltip.component.html
  src/angularjs/src/app/components/user-tooltip/user-tooltip.component.scss
  src/angularjs/src/app/components/user-tooltip/user-tooltip.component.ts
  src/angularjs/src/app/interfaces/user/user.interface.ts
  src/angularjs/src/app/services/user.service.ts
  src/nestjs/src/modules/database/user/entity.ts
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/websocket/game/game.service.ts
  src/nestjs/src/websocket/module.ts
  src/nestjs/src/websocket/socket.service.ts
Labels: 🚑️ CRITICAL, 📚 SUBJECT, 🔄 FRONT/BACK

#230 Fix login page
  src/angularjs/.editorconfig
  src/angularjs/src/app/pages/login/login.component.html
  src/angularjs/src/app/pages/login/login.component.scss
  src/angularjs/src/app/pages/login/login.component.ts
  src/nestjs/src/modules/auth/controller.ts
  src/nestjs/src/modules/auth/service.ts
  src/nestjs/src/websocket/gateway.ts
Labels: 🚑️ CRITICAL, 🔄 FRONT/BACK

#241 240 post grade
  src/angularjs/src/app/components/chat-view/chat-view.component.html
  src/angularjs/src/app/components/chat-view/chat-view.component.ts
  src/angularjs/src/app/pages/home-dashboard/home-dashboard.component.html
  src/angularjs/src/app/pages/home-dashboard/home-dashboard.component.ts
  src/angularjs/src/app/services/websocket/chat/chatroom.service.ts
  src/angularjs/src/favicon.ico
Labels: 📚 SUBJECT, 🔜 FRONT, POSTGRADE
