Repository Pixailz/ft_transcendence, pull requests merged in 2023-08, with the labels that each got.

#60 51-websocket-module
  build/nginx/default.conf
  docker-compose-dev.yaml
  setup
  src/angularjs/package-lock.json
  src/angularjs/package.json
  src/angularjs/src/app/app-routing.module.ts
  src/angularjs/src/app/app.module.ts
  src/angularjs/src/app/components/header/header.component.html
  src/angularjs/src/app/components/header/header.component.ts
  src/angularjs/src/app/environments/environment.dev.ts
  src/angularjs/src/app/environments/environment.ts
  src/angularjs/src/app/pages/chat/chat.component.html
  src/angularjs/src/app/pages/chat/chat.component.scss
  src/angularjs/src/app/pages/chat/chat.component.spec.ts
  src/angularjs/src/app/pages/chat/chat.component.ts
  src/angularjs/src/app/pages/register/register.component.ts
  src/angularjs/src/app/pages/user-profile/user-profile.component.ts
  src/angularjs/src/app/services/auth-guard.service.ts
  src/angularjs/src/app/services/back-req.service.ts
  src/angularjs/src/app/services/user.service.ts
  src/angularjs/src/app/services/ws-chat.ts
  src/nestjs/package-lock.json
  src/nestjs/package.json
  src/nestjs/src/app.module.ts
  src/nestjs/src/modules/api42/module.ts
  src/nestjs/src/modules/api42/service.ts
  src/nestjs/src/modules/auth/controller.ts
  src/nestjs/src/modules/auth/module.ts
  src/nestjs/src/modules/auth/service.ts
  src/nestjs/src/modules/database/chatRoom/controller.ts
  src/nestjs/src/modules/database/chatRoom/dto.ts
  src/nestjs/src/modules/database/chatRoom/entity.ts
  src/nestjs/src/modules/database/chatRoom/service.ts
  src/nestjs/src/modules/database/database.module.ts
  src/nestjs/src/modules/database/gameInfo/controller.ts
  src/nestjs/src/modules/database/gameInfo/dto.ts
  src/nestjs/src/modules/database/gameInfo/entity.ts
  src/nestjs/src/modules/database/gameInfo/service.ts
  src/nestjs/src/modules/database/message/controller.ts
  src/nestjs/src/modules/database/message/dto.ts
  src/nestjs/src/modules/database/message/service.ts
  src/nestjs/src/modules/database/user/controller.ts
  src/nestjs/src/modules/database/user/dto.ts
  src/nestjs/src/modules/database/user/module.ts
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/modules/database/userChatRoom/controller.ts
  src/nestjs/src/modules/database/userChatRoom/dto.ts
  src/nestjs/src/modules/database/userChatRoom/service.ts
  src/nestjs/src/modules/user/controller.ts
  src/nestjs/src/modules/user/module.ts
  src/nestjs/src/modules/user/user.controller.ts
  src/nestjs/src/modules/user/user.module.ts
  src/nestjs/src/modules/user/user.service.ts
  src/nestjs/src/modules/ws/chat/gateway.ts
  src/nestjs/src/modules/ws/chat/module.ts
Labels: ✨ ENHENCEMENT

#68 [angular] critters 0.0.19 => 0.0.20
  src/angularjs/package-lock.json
Labels: 🐛 BUG, 🚑️ CRITICAL

#78 [angular:user-profile] fix red message
  src/angularjs/src/app/pages/user-profile/user-profile.component.html
  src/angularjs/src/app/pages/user-profile/user-profile.component.ts
Labels: ❌ INVALID, 📚 SUBJECT

#85 [frontend] actually redirect to redirectUrl
  src/angularjs/src/app/pages/login/login.component.ts
Labels: ✨ ENHANCEMENT, 🔜 FRONT

#89 Ws little fix
  setup
  src/angularjs/src/app/pages/chat/chat.component.ts
  src/angularjs/src/app/services/chat.service.ts
  src/angularjs/src/app/services/ws-chat.gateway.ts
  src/nestjs/src/adapter/user/service.ts
  src/nestjs/src/websocket/chat/chat.service.ts
Labels: 🐛 BUG

#91 split file of the CI.yaml file
  .github/workflows/CI-docker.yaml
  .github/workflows/CI-nest.yaml
  .github/workflows/CI.yaml
Labels: 🤖 ACTIONS

#96 [front:guard] invoke auth guard on every route
  src/angularjs/src/app/app-routing.module.ts
  src/angularjs/src/app/pages/login/login.component.ts
  src/angularjs/src/app/services/auth-guard.service.ts
Labels: 🐛 BUG, 🔜 FRONT

#97 add deployment
  .env.template
  .github/workflows/CD.yaml
  .github/workflows/CI.yaml
  README.md
  build/nginx/Dockerfile
  build/nginx/entrypoint
  docker-compose.yaml
  setup
Labels: ✨ ENHANCEMENT, 🤖 ACTIONS

#93 2FA
  src/angularjs/package-lock.json
  src/angularjs/package.json
  src/angularjs/src/app/app-routing.module.ts
  src/angularjs/src/app/app.module.ts
  src/angularjs/src/app/components/twofaform/twofaform.component.css
  src/angularjs/src/app/components/twofaform/twofaform.component.html
  src/angularjs/src/app/components/twofaform/twofaform.component.spec.ts
  src/angularjs/src/app/components/twofaform/twofaform.component.ts
  src/angularjs/src/app/interfaces/chat.interface.ts
  src/angularjs/src/app/pages/login/login.component.html
  src/angularjs/src/app/pages/login/login.component.ts
  src/angularjs/src/app/pages/user-profile/user-profile.component.html
  src/angularjs/src/app/pages/user-profile/user-profile.component.ts
  src/angularjs/src/app/services/back.service.ts
  src/angularjs/src/app/services/user.service.ts
  src/nestjs/package-lock.json
  src/nestjs/package.json
  src/nestjs/src/adapter/user/controller.ts
  src/nestjs/src/app.module.ts
  src/nestjs/src/modules/auth/controller.ts
  src/nestjs/src/modules/auth/service.ts
  src/nestjs/src/modules/database/user/controller.ts
  src/nestjs/src/modules/database/user/dto.ts
  src/nestjs/src/modules/database/user/entity.ts
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/modules/twofa/twofa.controller.ts
  src/nestjs/src/modules/twofa/twofa.module.ts
  src/nestjs/src/modules/twofa/twofa.service.ts
  src/nestjs/src/websocket/chat/chat.service.ts
  src/nestjs/yarn.lock
Labels: 📚 SUBJECT, 🔙 BACK, 🔜 FRONT
