Repository Pixailz/ft_transcendence, pull requests merged in 2023-07, with the labels that each got.

#6 :lipstick:[frontend:header] add style to fix header spacer
  src/angularjs/src/app/header/header.component.scss
Labels: ✨ ENHENCEMENT

#2 Database Module
  README.md
  rsc/postman/postman
  rsc/postman/req/api/createUser
  rsc/postman/req/product/add1
  rsc/postman/req/product/add2
  rsc/postman/req/product/add3
  rsc/postman/req/product/del_one
  rsc/postman/req/product/get_all
  rsc/postman/req/product/get_one
  rsc/postman/req/product/patch_one
  rsc/postman/req/user/delete
  rsc/postman/req/user/get
  rsc/postman/req/user/get_id
  rsc/postman/req/user/post
  rsc/postman/req/user/put
  rsc/postman/req/userInfo/delete
  rsc/postman/req/userInfo/get
  rsc/postman/req/userInfo/get_id
  rsc/postman/req/userInfo/post
  rsc/postman/req/userInfo/put
  src/nestjs/src/app.module.ts
  src/nestjs/src/main.ts
  src/nestjs/src/modules/api42OAuth/api42OAuth.controller.ts
  src/nestjs/src/modules/api42OAuth/api42OAuth.service.ts
  src/nestjs/src/modules/database/database.module.ts
  src/nestjs/src/modules/database/user/controller.ts
  src/nestjs/src/modules/database/user/dto.ts
  src/nestjs/src/modules/database/user/entity.ts
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/modules/database/userInfo/controller.ts
  src/nestjs/src/modules/database/userInfo/dto.ts
  src/nestjs/src/modules/database/userInfo/entity.ts
  src/nestjs/src/modules/database/userInfo/service.ts
Labels: 🚑️ CRITICAL FEATURE

#14 13 cleaning after merge
  src/nestjs/src/modules/api42OAuth/api42OAuth.controller.ts
  src/nestjs/src/modules/api42OAuth/api42OAuth.service.ts
  src/nestjs/src/modules/database/user/controller.ts
  src/nestjs/src/modules/database/user/dto.ts
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/modules/database/userInfo/controller.ts
  src/nestjs/src/modules/database/userInfo/dto.ts
  src/nestjs/src/modules/database/userInfo/service.ts
Labels: ❌ INVALID

#16 Backend database
  src/nestjs/src/modules/database/user/controller.ts
  src/nestjs/src/modules/database/user/dto.ts
  src/nestjs/src/modules/database/user/entity.ts
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/modules/database/userInfo/entity.ts
Labels: ✨ ENHENCEMENT

#23 [BACK] JWT and Passport Integration
  .env.template
  docker-compose.yaml
  src/angularjs/angular.json
  src/angularjs/package-lock.json
  src/angularjs/src/app/app.module.ts
  src/angularjs/src/app/pages/login/login.component.ts
  src/angularjs/src/proxy.conf.json
  src/nestjs/package-lock.json
  src/nestjs/package.json
  src/nestjs/src/app.module.ts
  src/nestjs/src/main.ts
  src/nestjs/src/modules/api42/api42.module.ts
  src/nestjs/src/modules/api42/api42.service.ts
  src/nestjs/src/modules/api42OAuth/controller.ts
  src/nestjs/src/modules/api42OAuth/module.ts
  src/nestjs/src/modules/api42OAuth/service.ts
  src/nestjs/src/modules/auth/auth.controller.ts
  src/nestjs/src/modules/auth/auth.module.ts
  src/nestjs/src/modules/auth/auth.service.ts
  src/nestjs/src/modules/auth/jwt-auth.guard.ts
  src/nestjs/src/modules/auth/jwt.strategy.ts
  src/nestjs/src/modules/database/database.module.ts
  src/nestjs/src/modules/database/user/controller.ts
  src/nestjs/src/modules/database/user/entity.ts
  src/nestjs/src/modules/database/user/service.ts
  src/nestjs/src/modules/database/userInfo/controller.ts
  src/nestjs/src/modules/database/userInfo/entity.ts
  src/nestjs/src/modules/database/userInfo/service.ts
  src/nestjs/src/public.decorator.ts
Labels: 🚑️ CRITICAL FEATURE

#25 Makefile and company
  .env.template
  build/nginx/Dockerfile
  build/nginx/default.conf
  build/nginx/entrypoint
  build/nodejs/Dockerfile
  build/postgresql/entrypoint
  docker-compose.yaml
  setup
  src/angularjs/angular.json
  src/angularjs/package-lock.json
  src/angularjs/package.json
  src/nestjs/package.json
Labels: ✨ ENHENCEMENT

#37 fix healthcheck CI thing
  README.md
  build/postgresql/Dockerfile
  docker-compose-dev.yaml
  docker-compose.yaml
Labels: 🐛 BUG

#44 42 logout redirection
  src/angularjs/src/app/components/header/header.component.ts
Labels: ✨ ENHENCEMENT
